import data from './drop-data.json';
export type Variant = { name: string; hex: string; image: string };
export type Product = { id: string; name: string; category: string; audience: string; price: number; variants: Variant[]; limited: boolean; player?: string; description: string };
export const products: Product[] = data;
export const collection = products.filter(p => !p.limited);
export const editions = products.filter(p => p.limited);
export const categories = [...new Set(collection.map(p => p.category))];
export const players = ['Tapia', 'Galán', 'Coello', 'Chingotto'];
export const sizes = ['XS','S','M','L','XL'];
export const productColours = (product: Product) => product.variants;
export const productVariant = (product: Product, colour?: string) => product.variants.find(v => v.name === colour) ?? product.variants[0];
export const productSizes = (product: Product) => product.category === 'Accessories' ? ['One size'] : sizes;
export const money = (price: number) => price === 0 ? 'TBC' : new Intl.NumberFormat('en-CA', {style:'currency',currency:'CAD'}).format(price);
